### ISSUE TITLE
I'm of the opinion this is not quite magical enough.

### ISSUE THREAD

**Issue by mehcode** [concordusapps/inquire.js#1]
We need more ponies.

![Ponies](http://media.djangopony.com/img/magic-pony-django-wallpaper.png)

---

Also; in a much more serious light.. this repository should be called like `enquire.js` or js-enquire or something to indicate the language. But that's just my preference. Only because we'll eventually have to port back across the pond to python

**Comment by joneshf** [comment]
Well, we can conform to [fantasy land](https://github.com/puffnfresh/fantasy-land) and shove the logo in.  I'm pretty sure querystrings form at least a semigroup.

As far as the naming, [they](https://npmjs.org/doc/json.html#name) recommend not having js in the name.  What will we need to use this for in python?  Isn't this just supposed to generate querystrings and urls?  Also, enquire is already taken in the registry, so i'm going to rename it inquire.  I mean, we're not british anyway, so whatever.

**Comment by mehcode** [comment]
Yeah; the '.js' or 'node-' should not be in the name _in npm_ but I prefer it in the repository name. Look at chaplin for example.

**Comment by joneshf** [comment]
As @CactusCommander noted today, there's some unicorn action going on now.  And the repo has been renamed to inquire.js, which probably just killed a bunch of external stuff.
